{{- if and .Values.discoveryService.enabled .Values.discoveryService.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "discoveryService.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.discoveryService.labels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.discoveryService.labels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.discoveryService.serviceAccount.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.discoveryService.serviceAccount.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.discoveryService.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.discoveryService.annotations "context" $ ) | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.discoveryService.serviceAccount.automountServiceAccountToken }}
{{- end }}
