{{ if not .Values.orchestrator.scaledJob.triggers.authentication.provider }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orchestrator.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
data:
  AWS_ACCESS_KEY_ID: {{ .Values.orchestrator.scaledJob.triggers.metadata.awsAccessKeyID | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.orchestrator.scaledJob.triggers.metadata.awsSecretAccessKey | b64enc }}
{{- end }}
