{{- if and .Values.orchestrator.enabled .Values.orchestrator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "orchestrator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.orchestrator.labels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.orchestrator.labels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.orchestrator.serviceAccount.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.orchestrator.serviceAccount.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.orchestrator.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.orchestrator.annotations "context" $ ) | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.orchestrator.serviceAccount.automountServiceAccountToken }}
{{- end }}
