apiVersion: v1
kind: Secret
metadata:
  name: {{ include "elasticmq.fullname" . }}-secrets
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "elasticmq.labels.standard" . | nindent 4 }}
type: Opaque
data:
    AWS_ACCESS_KEY_ID: "{{ .Values.elasticMQ.aws.accessKeyId | b64enc }}"
    AWS_SECRET_ACCESS_KEY: "{{ .Values.elasticMQ.aws.secretAccessKey | b64enc }}"
