{{ if .Values.deployer.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deployer.fullname" . }}-auth-keys
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "deployer.labels.standard" . | nindent 4 }}
type: Opaque
data:
  ODIN_PUBLIC_KEY: {{ include "deployer.security.auth.publicKey" . | b64enc | quote }}
  ODIN_PRIVATE_KEY: {{ include "deployer.security.auth.privateKey" . | b64enc | quote }}
{{- end }}
