{{- if and .Values.deployer.enabled .Values.deployer.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "deployer.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.deployer.labels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.deployer.labels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.deployer.serviceAccount.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.deployer.serviceAccount.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.deployer.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.deployer.annotations "context" $ ) | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.deployer.serviceAccount.automountServiceAccountToken }}
{{- end }}
