apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mysql.backup.storages.s3local.s3.credentialsSecret }}
  labels:
    app: {{ .Release.Name }}-minio-s3-credentials
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
    AWS_ACCESS_KEY_ID: "{{ .Values.minio.rootUser | b64enc }}"
    AWS_SECRET_ACCESS_KEY: "{{ .Values.minio.rootPassword | b64enc }}"
