{{- if and .Values.accountManager.enabled .Values.accountManager.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "accountManager.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.accountManager.labels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.accountManager.labels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.accountManager.serviceAccount.annotations }}
      {{- include "common.tplvalues.render" ( dict "value" .Values.accountManager.serviceAccount.annotations "context" $ ) | nindent 4 }}
      {{- end }}
      {{- if .Values.accountManager.annotations }}
      {{- include "common.tplvalues.render" ( dict "value" .Values.accountManager.annotations "context" $ ) | nindent 4 }}
      {{- end }}
automountServiceAccountToken: {{ .Values.accountManager.serviceAccount.automountServiceAccountToken }}
  {{- end }}
