name: Release Chart

on:
  push:
    branches:
      - master
    paths:
      - "charts/odin/Chart.yaml"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "release-bot"
          git config user.email "release-bot@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1

      - name: Add dependency chart repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add minio https://charts.min.io/
          helm repo add percona https://percona.github.io/percona-helm-charts/
          helm repo add discovery-controller https://dream-horizon-org.github.io/odin-discovery-controller/

      - name: Update Chart.lock
        working-directory: charts/odin
        run: helm dependency update

      - name: Lint chart
        working-directory: charts/odin
        run: helm lint .

      - name: Publish helm chart
        working-directory: charts
        run: |
          helm package odin
          VERSION=$(yq -r '.version' odin/Chart.yaml)
          helm push odin-${VERSION}.tgz ${{ vars.HELM_REGISTRY }}/${{ vars.HELM_REPOSITORY }} --username ${{ secrets.HELM_USERNAME }} --password ${{ secrets.HELM_PASSWORD }}
